project_id = "gaxxwzlmykymqcgrlcqr"

[functions.cartoncloud]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.carrier-booking]
verify_jwt = false

[functions.recaptcha-config]
verify_jwt = false

[functions.accept-invite-by-email]
verify_jwt = true

[functions.carrier-working-hours]
verify_jwt = false

[functions.cartoncloud-credentials]
verify_jwt = true
